### PR TITLE
Page meta titles can now be localized

### PR DESCRIPTION
**Pull request by MatissJanis**
Slightly more info can be found here: https://medium.com/@matissjanis/octobercms-localized-title-meta-tag-b18d368ca953

### CODE REVIEW

**Comment by MatissJanis** [comment]
This solves #70

**Comment by daftspunk** [comment]
`<title>{{ this.page.title|_ }}</title>` ?

**Comment by MatissJanis** [comment]
Haha.. I'm always choosing the difficult path. Thanks for pointing out this simple solution!

**Comment by Alex360hd** [comment]
The twig {{ this.page.title|_ }} works but why not just adding a language switcher to meta title and description exactly like others translatable fields ?

Basically, I would imagine you just have to add the meta title and description fields to $translatable array, isn't it ?

**Comment by LukeTowers** [comment]
@Alex360hd give it a try, see if you can make a simple PR to make it work. Ping me when it's ready for review :)

**Pull request closed without merging**
