### PR TITLE
Fixes issue with indexing

### PR DESCRIPTION
**Pull request by panakour**
Reference #481 

Peek 2019-05-13 09-21

october:454
translate: 1.6.0
pages: 1.2.21

### CODE REVIEW

**Comment by bennothommo** [comment]
@panakour This may not be needed - this PR to October core might resolve the issue for you:
https://github.com/octobercms/october/pull/4334

**Comment by mjauvin** [comment]
Definitely NOT getting this behavior, even without PR #4334.

**Comment by w20k** [comment]
@panakour could you re-test your bug with the latest build.

**Comment by panakour** [comment]
@w20k The issue keep exists.

image

**Comment by mjauvin** [comment]
Can anybody else reproduce this? @bennothommo @LukeTowers @w20k ?!

**Comment by w20k** [comment]
@panakour could you provide a code block for `Misc tab`? So, it would be easier to reproduce your test case.

**Comment by panakour** [comment]
> @panakour or @mjauvin could you guys provide a code block for `Misc tab`?
> So, it would be easier to reproduce your test case.

```
{repeater name="content_sections" prompt="Add another content section"}
<h3>
    {text name="content_header" label="Content section" placeholder="Type in a heading and enter some content for it below"}{/text}
</h3>
<div>
    {richeditor name="content_body" size="large"}{/richeditor}
</div>
{/repeater}
```

**Comment by mjauvin** [comment]
```
{repeater name="content_sections" prompt="Add another content section"}
<h3>
    {text name="content_header" label="Content section" placeholder="Type in a heading and enter some content for it below"}{/text}
</h3>
<div>
    {richeditor name="content_body" size="large"}{/richeditor}
</div>
{/repeater}
```

**Comment by w20k** [comment]
Tested and it works as it should, with a clean install and the latest changes.
Screenshots:
Screenshot 2019-05-16 at 17 14 33
Screenshot 2019-05-16 at 17 15 21

**Comment by panakour** [comment]
@w20k is it ok that indexes not reindex and start from zero?

**Comment by bennothommo** [comment]
@w20k I was under the impression the correct behaviour is that when the page is saved, the repeater items should be saved into the viewBag starting from index 0, even if you have say 2 items and delete the first. That bottom image doesn't look right.

**Comment by mjauvin** [comment]
Am I the only one getting the "correct" behavior!? For me, indexes properly end-up starting at 0 whatever I try...

**Comment by w20k** [comment]
@panakour @bennothommo 
Don't rush to a conclusion. What I've meant - just did a smoke test run of an issue, and I've tested PR yet, it was working the same way as it was few builds ago.

**Comment by bennothommo** [comment]
It's currently working that way for me too @mjauvin.

**Comment by mjauvin** [comment]
Where are we on this? Looks like @bennothommo and myself have the correct behavior without this PR, and @w20k and @panakour have the wrong behavior. Is that correct? What are we missing?

**Comment by mjauvin** [comment]
@w20k can you test this again, I'd really like to close this as it's been working fine for me for a while now...

**Comment by w20k** [comment]
@mjauvin sure will run few tests today.

**Comment by w20k** [comment]
@mjauvin fix is working!

What I did:
**1st**   run added `1` and `2`
**2nd** run removed `2`
**3d**   run removed `2` and added `3` and `4`

Screenshots (with patch):
Screenshot 2019-06-07 at 15 13 00
Screenshot 2019-06-07 at 15 13 23
with_patch_clean_after_initial03

Screenshots (without patch):
Screenshot 2019-06-07 at 15 18 29
Screenshot 2019-06-07 at 15 18 47
Screenshot 2019-06-07 at 15 19 09

**Comment by haralake** [comment]
Using this fix when i switch language and try to save static page without any repeater field i get this error:

```"array_values() expects parameter 1 to be array, null given" on line 67 of /....../....../plugins/rainlab/translate/formwidgets/MLRepeater.php
```
If i create a repeater field i can save it properly without error.

**Comment by mjauvin** [comment]
Can you see if #491 fixes this for you?

**Pull request merged**
