### PR TITLE
Import & Export Messages

### PR DESCRIPTION
**Pull request by munxar**

### CODE REVIEW

**Comment by viezel** [comment]
very nice! I hope this feature get introduced soon.

**Comment by LukeTowers** [comment]
@viezel @munxar @viamage could you post screenshots and test this change thoroughly and let me know if it's all good to go or if any changes are recommended?

**Comment by munxar** [comment]
@LukeTowers I'm finished with the implementation. For what reason do you need screenshots? Documentation?

**Comment by viezel** [comment]
@LukeTowers 

*export:* http://prntscr.com/id9d3l
In my test export works, but the character `"` breaks the export, if its part of a string. 

*import:* http://prntscr.com/id9ij8
*import status:* http://prntscr.com/id9kcx 
Import works 👍 

unfortunately, it does not export: `CMS -> pages`, `Blog -> posts`, `Pages -> Pages` meaning translating the table `rainlab_translate_attributes` which could have been cool. But its a great start 👍

**Comment by munxar** [comment]
@viezel thank you for taking the time and testing it.
It was never planned to export the mentioned backend parts, only the messages you see in the table.
To be honest, it would be a cool feature to have all data exported an imported. But discuss this in a new feature request and start this as a MVP.

**Comment by munxar** [comment]
@LukeTowers I added some unit tests for export and import model to cover the implementation logic.

**Comment by LukeTowers** [comment]
@munxar @viezel @viamage @alvaro-canepa is this ready to merge now?

**Comment by munxar** [comment]
@LukeTowers  from my point of view, yes.

**Comment by alvaro-canepa** [comment]
@LukeTowers it looks great! after testing and using, maybe we find some bugs to fix. Like say @viezel on export thirth plugin translations

**Pull request merged**
