### PR TITLE
Allows to export default locale

### PR DESCRIPTION
**Pull request by Samuell1**
Fixes #422 

Reworked original PR from few years ago #431

### CODE REVIEW

**Comment by mjauvin** [comment]
Samuell, it would need to be triggered by an additional checkbox to be accepted, otherwise it will break the current behavior. (e.g. include original key)

**Comment by Samuell1** [comment]
@mjauvin yes you can disable it or enabled in export menu.

**Comment by mjauvin** [comment]
@Samuell1 could you set this new column to UNCHECKED by default to keep existing behavior?

**Comment by Samuell1** [comment]
@mjauvin Not sure if ocms supports that for export.

**Pull request merged**
