### PR TITLE
fix date translation

### PR DESCRIPTION
**Pull request by munxar**
This fixes bug https://github.com/rainlab/translate-plugin/issues/338

### CODE REVIEW

**Comment by LukeTowers** [comment]
@munxar this results because of https://github.com/laravel/framework/commit/3385fdc0f8e4890ab57261755bcbbf79f9ec828d#diff-7b18a52eceff5eb716c1de268e98d55dR1045 added in Laravel 5.4. A more robust fix will have to be made in the octobercms/library repository and we need to evaluate if any more events have been modified accordingly.

**Comment by LukeTowers** [comment]
Other changed events listed here: https://laravel.com/docs/5.4/upgrade. @daftspunk did you handle this in the upgrade?

**Comment by daftspunk** [comment]
Fixed in core (https://github.com/octobercms/library/commit/16f7a286d8c90fb114d3abc9f7a51218c414c1f7)

This will be available in build 433+

**Comment by amdad** [comment]
"legacy" will stay forever in core? So this PR fix for Translate plugin will not be needed, ever since 433?

**Pull request closed without merging**
