### PR TITLE
search feature

### PR DESCRIPTION
**Pull request by dev-lav**
Added search feature to make it easier for users with lots of data to translate.
Thank you.

### CODE REVIEW

**Comment by LukeTowers** [comment]
I don't have a ton of time to review this right now, so if somebody was able to take screenshots of this in action (or even better a GIF) as well as confirm that it works, I'd love to merge it.

Thanks for your work so far @dev-lav!

**Comment by daftspunk** [comment]
As above. Thanks @dev-lav

**Comment by jan-vince** [comment]
Hi, I have tried this, but have no time to dig much deeper:

* 'Search ...' should be replaced with translation ```` e(trans('backend::lang.list.search'))````.
* Search should use AJAX to be consistent across October backend (right now I have to hit Enter key to search).
* For me, search works only for default language. 
* After search, list is reversed to default view (so if I choose different language in list header, after search it's back in default).

What do you think about these points?

**Comment by LukeTowers** [comment]
@dev-lav See if you can integrate the [search widget](https://github.com/octobercms/october/blob/master/modules/backend/widgets/Search.php) in a similar fashion to how the ListsController behaviour does already. If the docs are sparse on it, try to figure it out as much as possible, and then I would very much welcome a PR to add more inline documentation to the code so that the [API documentation for that widget](http://octobercms.com/docs/api/backend/widgets/search) would be improved.

**Comment by daftspunk** [comment]
Added seaching to the table widget instead fb007dfb7b7968df8f766c7da5b4c0d565a81841

Note Translate 1.3.0+ requires Build 420+

**Comment by daftspunk** [comment]
BTW - great contribution @dev-lav!

**Comment by dev-lav** [comment]
Thank you @daftspunk

**Pull request merged**
