### PR TITLE
Update lang/pl/lang.php

### PR DESCRIPTION
**Pull request by mikolajklek**
Fixed typos, and uptaded pl language to latest version

### CODE REVIEW

**Comment by mjauvin** [comment]
Please leave the opening php tag on its own line and keep the spacing before the return.

**Comment by LukeTowers** [comment]
@mjauvin I will note that I personally prefer that the return statement is on the same line as the opening PHP tag for language files, but we haven't enforced one way or the other throughout our codebase yet.

**Comment by LukeTowers** [comment]
@mjauvin if you're up for it these tests need to be fixed by forcing Composer to 1.0 for now like Ben did in the main repo, or you could test the Composer 2.0 fix PR in the wikimedia-merge-plugin with October so that we can move onto the next version of that plugin and the tests will fix themselves.

**Comment by mjauvin** [comment]
Thanks for your contribution @mikolajklek!

**Pull request merged**
