### PR TITLE
[WIP] localized mail templates

### PR DESCRIPTION
**Pull request by mjauvin**
use mail templates with locale suffix if it exists

fixes: #533

### CODE REVIEW

**Comment by mjauvin** [comment]
- cannot use localized templates for privileged routes (e.g. /backend/auth)
- localized mail templates must be registered using "author.plugin::mail.template-LOCALE" (e.g. `rainlab.translate::mail.notification-fr`)

**Comment by mjauvin** [comment]
@daftspunk are you sure the current locale would be available for a queued mail ?

**Comment by daftspunk** [comment]
> @daftspunk are you sure the current locale would be available for a queued mail ?

It would appear not :(

**Comment by mjauvin** [comment]
@daftspunk you're saying the locale is not available for a queued mail, can you provide a reproducible test for this?

**Pull request closed without merging**
