### PR TITLE
Empty translations replacement

### PR DESCRIPTION
**Pull request by mod3st**
Added the ability to return the original models attribute values for empty translations.
Using example: $model->lang('pl')->skipEmptyTranslations()

### CODE REVIEW

**Comment by daftspunk** [comment]
I think this should be enabled by default and it should be called "fallback".

So `$model->lang('pl')->noFallback()` would mean empty values are empty and do not fall back to the default language.

**Comment by mod3st** [comment]
Hey, just added proposed changes:
- "fallback" calls
- fallbacks as default option

**Comment by mod3st** [comment]
Hey, what about this change?

**Comment by daftspunk** [comment]
Sorry - was busy with RC, finally found the time. 

Thanks for this!

**Comment by daftspunk** [comment]
Note I have renamed `noFallbackTranslations` to  `noFallbackLocale`

**Pull request merged**
