### PR TITLE
fix #482 issue

### PR DESCRIPTION
**Pull request by mjauvin**
make sure $value is an array when using array_values

### CODE REVIEW

**Comment by mjauvin** [comment]
@haralake try this fix

**Comment by haralake** [comment]
Yes that fixes the error. When i switch language, create a field and save it data saved properly, but for some weird reason when i delete the field i created and save it data doesn't removed, are still here.

**Comment by mjauvin** [comment]
Not sure I understand what you mean.

**Comment by haralake** [comment]
Let me explain:
1 .On static page switch language with language selector
2. Create one field using repeater field and save page
3. Delete this field you have created and save page
4. On static page content that keeps fields data you will see that data are still there, they have not been deleted

**Comment by mjauvin** [comment]
Ok, I didn't test this yet, but does it create problems other than having left-over data?

Would you consider this a seperate issue? If so, can you open a new issue for this?

**Comment by haralake** [comment]
Sorry for delay! Ok i will create a new issue for this, thank you.

**Pull request merged**
