### PR TITLE
fix MLRepeater bug when switching locales

### PR DESCRIPTION
**Pull request by munxar**

### CODE REVIEW

**Comment by Fl0Cri** [comment]
This fix works well when used from static pages plugin.

To test more complex repeaters, we need to use define them in a yaml file. So I did some tests using the [test plugin](https://github.com/daftspunk/oc-test-plugin). The **Countries** section have some repeaters, but these are not translatable out of box. To reproduce my tests, you will need to add the following class properties in [/plugins/october/test/models/Country.php](https://github.com/daftspunk/oc-test-plugin/blob/master/models/Country.php#L11):
```PHP
public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['locations', 'states', 'content'];
```

Note that I didn't test everything without the fix to compare results. I only tested when it made sense to me. In any case the "without fix" behaviour is to load the values from the default lang in place of the translated ones as described in #323.

The following schema is repeated to test each repeater type:
1. Create a fresh country and save it
1. From default locale, insert some values
1. Switch to a secondary locale
1. Insert some values
1. Save, switch back to the default locale and check the loaded values
1. Reload the page and check the values
1. Switch to the secondary locale and check the values
1. Switch bacl to the default locale and check the values

### Classic repeaters
> Found in the "Related" tab of a "Country" item, it looks like what we can do using the static pages plugin. Note that the repeater contains 2 dropdowns, with a specificity being that the second one depends on the first one.
1. Create Country - *ok*
1. Insert values - *ok* (changing the value of the first dropdown correctly affect the available options in the second one)
1. Switch locale - *ok* (repeater is cleared)
1. Insert values - *ok*
1. Save and switch locale - *ok* (values from the default locale are displayed)
1. Reload - *ok* (values from the default locale are displayed)
1. Switch locale - *ok*
1. Switch locale back to default - *ok*

In this classic use case, everything works fine. 

### Nested repeaters
> Found in the "States" tab of a "Country" item. Basically it's a repeater with each node having a text field and a repeater (sub repeater nodes having only a text field).

For this test I try to insert the following values:
```
Test [lang]
    |---- SubTest [lang]

Test2 [lang]
```

1. Create Country - *ok*
1. Insert values - *ok*
1. Switch locale - *ok*
1. Insert values - *ok*
1. Save & switch locale - *ok*
1. Reload - *ok*
1. Switch locale - **problem:** now inside `Test2 FR`, there is an empty text field that's not supposed to be here.
1. Switch locale back to default - **the empty text field is also here now**

Note: I tested the 2 last points without the fix, and the problem of an emty sub field being created is also present.
So this bug was **not** introduced by this fix. I will open an other issue, but I won't have time to investigate on it for now.

### Grouped repeaters
> Found in the "Content" tab of a "Country" item

For this test I try to insert a text content and an image (with different values and order for different languages)

1. Create Country - *ok*
1. Insert values - *ok*
1. Switch locale - *ok*
1. Insert values - *ok*
1. Save & switch locale - *ok*
1. Reload - *ok*
1. Switch locale - *ok*
1. Switch locale back to default - **problem:** the english version is empty

Note: I found after testing that it's exactly the problem pointed out by @munxar in https://github.com/rainlab/translate-plugin/issues/290: it is because in my test i had the textarea first and the image after in EN version, and the image first and textarea after in FR. If I use the same order in both language, the test is ok.

**Comment by munxar** [comment]
@Fl0Cri Yes, exactly. To fix the repeaters with groups or repeater in repeater, which is basically the same, we need another fix. But this PR at least makes the repeater work again for average cases.
Btw. Thank you very much for the detailed testing!

**Comment by jan-vince** [comment]
Hi, for me this fix works for Static pages and plugin form fields standard repeaters.

Would be great if this can be merged :)

**Comment by LukeTowers** [comment]
@Fl0Cri @munxar @jan-vince final verdict is that this fix works and doesn't break anything else?

**Comment by jan-vince** [comment]
@LukeTowers I have been testing this with and without Translate plugin and everything looks OK.

Without this fix I cannot use repeater with more than one language.

*All other translatable form fields (like text, richeditor) works form me as before.*

Proof of this working:

october-fix-mlrepeater

**Comment by Fl0Cri** [comment]
@LukeTowers I think it's safe to merge. Even if it breaks something that we didn't see, it will only impact this isolated part of the code (the onSwitchItemLocale ajax handler), and this feature actually doen't work at all ;-)

**Comment by LukeTowers** [comment]
Perfect, thanks for all the work on this @Fl0Cri @munxar @jan-vince!

**Pull request merged**
