### PR TITLE
Greek language added

### PR DESCRIPTION
**Pull request by msRob0t**
Could you please label my request as hacktoberfest-accepted?

### CODE REVIEW

**Comment by mjauvin** [comment]
Please, rename file to `lang/gr/lang.php` (no .txt extension)

**Comment by mjauvin** [comment]
the ". php" extension is missing.

**Comment by mjauvin** [comment]
May I ask how you translated these strings?

**Comment by msRob0t** [comment]
> May I ask how you translated these strings?

Im greek. I used google translate to save time and afterwards checked if the meaning was ok. if not i modified the sentences. i matched the meaning as much as i could.

**Comment by mjauvin** [comment]
Excellent!

**Pull request merged**
