### PR TITLE
Add operator to where clause

### PR DESCRIPTION
**Pull request by Rike-cz**
Fix issue #418.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@munxar @osmanzeki could you take a look?

**Comment by mjauvin** [comment]
@Rike-cz has this been tested so far? If you could add some Unit tests to help verify this, I would definitely merge this.

**Comment by LukeTowers** [comment]
@mjauvin I'm not sure this could necessarily be unit tested. If @Rike-cz could provide an example use case that is broken in the current behaviour but fixed by this PR then that should be all that we need to get this merged (after testing it of course)

**Comment by w20k** [comment]
Would be nice to have an example use case from @Rike-cz, and it's good to go.

**Comment by Rike-cz** [comment]
That was only missing `$operator` in where clause when comparing with value as in line bellow, where input value is compared with value in translate table. I do not have use case for this now, but you can simply use `!=` or `LIKE` and compare it with some wildcards, for example: `$query->transWhere('slug', 'test', null, '!=')`.

**Comment by mjauvin** [comment]
@rike-cz can you provide behavior before and after the change? Have you used the transWhere() method with this modification?

**Comment by mjauvin** [comment]
Ok, so basically, before this change, since the $operator was NOT provided to the where() method of the query, the DEFAULT operator (=) for where() method was used.

With this change, as long as NO operator is provided to transWhere() method, the behavior will stay the same since the default value of the $operator argument to transWhere() is also "=".

The only difference is that we can now provide a different operator to transWhere and it will be passed to the where() method of the query.

**Comment by LukeTowers** [comment]
@mjauvin please make sure you update the labels as appropriate after taking action on an issue / PR.

**Pull request merged**
