### PR TITLE
Add Rich Editor widget support.

### PR DESCRIPTION
**Pull request by mod3st**
Also MLControl refactor - abstract turned into trait allowing "ML..." classes inheritance form default widgets.

### CODE REVIEW

**Comment by mod3st** [comment]
This feature requires another proposed change, but in october package:
https://github.com/octobercms/october/pull/882

**Comment by daftspunk** [comment]
Is this based on the work in the `richeditor` branch?

**Comment by mod3st** [comment]
No, I didn't noticed that it is a branch :)

**Comment by daftspunk** [comment]
I have merged the two together, these features are now available in the master branch

**Comment by daftspunk** [comment]
Thanks!

**Pull request closed without merging**
